# Generated by Django 5.1.4 on 2025-06-05 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('imap_host_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('folder', models.CharField(max_length=10)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.emailaccount')),
            ],
        ),
    ]
