# Generated by Django 5.2.2 on 2025-06-17 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('imap_host_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sender', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('sender_email', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('folder', models.CharField(max_length=255)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.emailaccount')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMonitoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.emailaccount')),
            ],
        ),
    ]
