# Generated by Django 5.2.2 on 2025-06-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_emailmessage_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='folder',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='sender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
