# Generated by Django 5.2.2 on 2025-06-13 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_emailaccount_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMonitoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.emailaccount')),
            ],
        ),
    ]
