# Generated by Django 5.2.2 on 2025-06-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_emailmonitoringresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailaccount',
            old_name='email_user_name',
            new_name='email_address',
        ),
    ]
